# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [3]:
print(np.__version__)
np.show_config()


2.3.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-sj75qq4o/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-sj75qq4o/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy/numpy/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-sj75qq4o/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-sj75qq4o/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [14]:
a = np.random.random((2, 3, 5))



### 4. Print a.


In [15]:
print(a)

[[[0.92082085 0.11701195 0.76486913 0.29425175 0.72137151]
  [0.99297686 0.0666854  0.75715025 0.35071629 0.9401273 ]
  [0.08945832 0.59999882 0.36058309 0.92155469 0.69222842]]

 [[0.68596204 0.52514056 0.29925902 0.70246045 0.48682456]
  [0.48427413 0.56293561 0.66831913 0.20814258 0.67470006]
  [0.76771593 0.14123747 0.3956306  0.56009732 0.4345829 ]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [23]:
b = np.ones((5, 2, 3))



### 6. Print b.


In [24]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [29]:
print(a.size == b.size)

True



### 8. Are you able to add a and b? Why or why not?


In [30]:
### [your code here]
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [39]:
c = np.transpose(b, (1, 2, 0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [40]:
d = a + c
print(d)


[[[1.92082085 1.11701195 1.76486913 1.29425175 1.72137151]
  [1.99297686 1.0666854  1.75715025 1.35071629 1.9401273 ]
  [1.08945832 1.59999882 1.36058309 1.92155469 1.69222842]]

 [[1.68596204 1.52514056 1.29925902 1.70246045 1.48682456]
  [1.48427413 1.56293561 1.66831913 1.20814258 1.67470006]
  [1.76771593 1.14123747 1.3956306  1.56009732 1.4345829 ]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [36]:
print(a)
print(d)



[[[0.92082085 0.11701195 0.76486913 0.29425175 0.72137151]
  [0.99297686 0.0666854  0.75715025 0.35071629 0.9401273 ]
  [0.08945832 0.59999882 0.36058309 0.92155469 0.69222842]]

 [[0.68596204 0.52514056 0.29925902 0.70246045 0.48682456]
  [0.48427413 0.56293561 0.66831913 0.20814258 0.67470006]
  [0.76771593 0.14123747 0.3956306  0.56009732 0.4345829 ]]]
[[[1.92082085 1.11701195 1.76486913 1.29425175 1.72137151]
  [1.99297686 1.0666854  1.75715025 1.35071629 1.9401273 ]
  [1.08945832 1.59999882 1.36058309 1.92155469 1.69222842]]

 [[1.68596204 1.52514056 1.29925902 1.70246045 1.48682456]
  [1.48427413 1.56293561 1.66831913 1.20814258 1.67470006]
  [1.76771593 1.14123747 1.3956306  1.56009732 1.4345829 ]]]



### 12. Multiply a and c. Assign the result to e.


In [42]:
e = a*c
print(e)


[[[0.92082085 0.11701195 0.76486913 0.29425175 0.72137151]
  [0.99297686 0.0666854  0.75715025 0.35071629 0.9401273 ]
  [0.08945832 0.59999882 0.36058309 0.92155469 0.69222842]]

 [[0.68596204 0.52514056 0.29925902 0.70246045 0.48682456]
  [0.48427413 0.56293561 0.66831913 0.20814258 0.67470006]
  [0.76771593 0.14123747 0.3956306  0.56009732 0.4345829 ]]]




### 13. Does e equal to a? Why or why not?


In [43]:
print(e.size == a.size)



True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [49]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max)
print(d_min)
print(d_mean)


1.9929768570751505
1.0666854046644225
1.5395695669678529



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [52]:
f = np.empty((2, 3, 5))
print(f)

[[[0.92082085 0.11701195 0.76486913 0.29425175 0.72137151]
  [0.99297686 0.0666854  0.75715025 0.35071629 0.9401273 ]
  [0.08945832 0.59999882 0.36058309 0.92155469 0.69222842]]

 [[0.68596204 0.52514056 0.29925902 0.70246045 0.48682456]
  [0.48427413 0.56293561 0.66831913 0.20814258 0.67470006]
  [0.76771593 0.14123747 0.3956306  0.56009732 0.4345829 ]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [53]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75
print(f)

[[[ 75.  25.  75.  25.  75.]
  [100.   0.  75.  25.  75.]
  [ 25.  75.  25.  75.  75.]]

 [[ 75.  25.  25.  75.  25.]
  [ 25.  75.  75.  25.  75.]
  [ 75.  25.  25.  75.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [55]:
print(d)
print(f)



[[[1.92082085 1.11701195 1.76486913 1.29425175 1.72137151]
  [1.99297686 1.0666854  1.75715025 1.35071629 1.9401273 ]
  [1.08945832 1.59999882 1.36058309 1.92155469 1.69222842]]

 [[1.68596204 1.52514056 1.29925902 1.70246045 1.48682456]
  [1.48427413 1.56293561 1.66831913 1.20814258 1.67470006]
  [1.76771593 1.14123747 1.3956306  1.56009732 1.4345829 ]]]
[[[ 75.  25.  75.  25.  75.]
  [100.   0.  75.  25.  75.]
  [ 25.  75.  25.  75.  75.]]

 [[ 75.  25.  25.  75.  25.]
  [ 25.  75.  75.  25.  75.]
  [ 75.  25.  25.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [56]:
g = np.empty(d.shape, dtype=object)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                g[i, j, k] = "A"
            elif d[i, j, k] == d_max:
                g[i, j, k] = "E"
            elif d[i, j, k] == d_mean:
                g[i, j, k] = "C"
            elif d_min < d[i, j, k] < d_mean:
                g[i, j, k] = "B"
            elif d_mean < d[i, j, k] < d_max:
                g[i, j, k] = "D"

print(g)

[[['D' 'B' 'D' 'B' 'D']
  ['E' 'A' 'D' 'B' 'D']
  ['B' 'D' 'B' 'D' 'D']]

 [['D' 'B' 'B' 'D' 'B']
  ['B' 'D' 'D' 'B' 'D']
  ['D' 'B' 'B' 'D' 'B']]]
